harobert1991/TUCA

app/models/category.rb

adding depedency

---

app/controllers/categories_controller.rb
app/controllers/recipes_controller.rb
app/views/categories/index.html.erb
app/views/categories/show.html.erb
app/views/recipes/index.html.erb
app/views/recipes/show.html.erb
config/routes.rb
db/schema.rb
test/controllers/categories_controller_test.rb
test/controllers/recipes_controller_test.rb

- Recipes controller
- Categories controller

2 controllers created

---

app/assets/stylesheets/config/_fonts.scss
app/views/layouts/application.html.erb

Added two types of fonts: 
- Enriqueta for titles 
- Luka for the texts

Added two types of fonts: Enriqueta for titles and Luka for the texts

---

db/seeds.rb

Created one seed for:
- category
- recipe

Created seeds for category and recipe

---

Gemfile
Gemfile.lock
app/assets/stylesheets/application.scss
app/assets/stylesheets/components/_navbar.scss
app/views/shared/_navbar.html.erb

bottom navbar

---

app/controllers/recipes_controller.rb
app/views/categories/index.html.erb
app/views/recipes/index.html.erb
config/routes.rb

- recipe index is filtered by category

filter by category

---

app/views/layouts/application.html.erb
app/views/shared/_navbar.html.erb

- activating link to home in navbar

link_to root in navbar

---

app/controllers/steps_controller.rb
app/models/recipe.rb
app/models/step.rb
app/views/steps/index.html.erb
config/routes.rb
db/migrate/20180327131958_create_steps.rb
db/schema.rb
db/seeds.rb
test/controllers/steps_controller_test.rb
test/models/step_test.rb

Steps model created
Steps view for index created
Routes for steps created

Added the steps model to the previous recipe and category models, view working as well, need to style the view

---

db/migrate/20180326124203_create_categories.rb
db/migrate/20180328083516_add_photo_to_category.rb
db/schema.rb
db/seeds.rb

db changes and photo migration

---

app/models/recipe.rb
db/seeds.rb

Resolving seeding problems because of the dependent::destroy

Resolving seeding problems because of the dependent::destroy

---

app/assets/stylesheets/components/_recipe_show.scss
app/views/layouts/application.html.erb
app/views/recipes/index.html.erb
app/views/recipes/show.html.erb
config/routes.rb
db/seeds.rb

linking pages

---

app/assets/stylesheets/components/_step_index.scss
app/views/steps/index.html.erb
db/seeds.rb

- Added "Next Step" buttons
- Designed the "Steps" page
- Added "tool icons" to the page
- Need some JS to scroll down to next step

Designed and added some content to the steps. Added Next Step buttons

---

app/assets/stylesheets/components/_step_index.scss

- Small changes to make the code work
- Resize the icons img

Small changes to make the code work and resize the size of the icons

---

app/assets/stylesheets/components/_devise_forms.scss
app/assets/stylesheets/components/_index.scss
app/controllers/carts_controller.rb
app/controllers/pages_controller.rb
app/controllers/recipes_controller.rb
app/models/cart.rb
app/models/recipe.rb
app/models/user.rb
app/views/carts/destroy.html.erb
app/views/carts/index.html.erb
app/views/devise/sessions/new.html.erb
app/views/recipes/show.html.erb
app/views/shared/_navbar.html.erb
config/routes.rb
db/migrate/20180329101738_create_carts.rb
db/migrate/20180329125728_add_recipe_to_carts.rb
db/schema.rb
test/controllers/carts_controller_test.rb
test/models/cart_test.rb

cart is in progress

---

app/assets/stylesheets/components/_cart_index.scss
app/assets/stylesheets/components/_index.scss
app/views/carts/index.html.erb

- adding checkboxes to cartlist 🛒

adding checkboxes to the cart

---

app/views/steps/index.html.erb

Design of steps finished for now

Design of steps completed ... for now

---

app/views/carts/index.html.erb
app/views/layouts/application.html.erb

- adding title and navbar to the   🛒

adding title and navbar to cart

---

app/controllers/favorites_controller.rb
app/controllers/pages_controller.rb
app/models/favorite.rb
app/models/recipe.rb
app/models/user.rb
app/views/favorites/create.html.erb
app/views/favorites/destroy.html.erb
app/views/favorites/new.html.erb
app/views/pages/dashboard.html.erb
app/views/recipes/show.html.erb
app/views/shared/_dashboard_card.html.erb
config/routes.rb
db/migrate/20180402073442_create_favorites.rb
db/schema.rb
test/controllers/favorites_controller_test.rb
test/models/favorite_test.rb

- do a rails db:migrate, new model for favorite
- we can now like the recipe and see them on our dashboard ❤️

adding likes, liked rec to dashboard and dislike btn

---

app/views/pages/dashboard.html.erb

- adding sign out button on dashboard

adding sign out button

---

app/views/devise/shared/_links.html.erb
db/schema.rb

- adding fb button to the login page

adding fb login button

---

app/controllers/carts_controller.rb
app/models/cart.rb
app/views/carts/index.html.erb
app/views/steps/index.html.erb
config/routes.rb

- adding a destroy cart button

Cartdestroy

---

app/assets/stylesheets/components/_carousel.scss
app/assets/stylesheets/pages/_home.scss
app/controllers/categories_controller.rb
app/controllers/recipes_controller.rb
app/views/categories/index.html.erb
app/views/layouts/application.html.erb
app/views/steps/index.html.erb

- Random picker of a recipe
- Redesigning of the home page

Random picker of a recipe and redesign of home page

---

db/migrate/20180403155124_remove_multiplier_from_doses.rb
db/schema.rb

- removing multiplier from doses

removing multiplier from doses

---

db/seeds.rb

seeding recipes + categories + changing pictures

---

app/assets/stylesheets/components/_carousel.scss
app/assets/stylesheets/pages/_home.scss
app/views/categories/index.html.erb

- When scrolling up, navbar disappears
- No more white header-border but text (TUCA) included in the picture

Home page design

---

app/assets/stylesheets/components/_step_index.scss

Fixing some sizes for the steps design

Is working better than the master even if it is not working for both recipes

---

app/views/layouts/application.html.erb

- adding meta tags to main html

adding meta tags

---

public/404.html
public/422.html
public/500.html

adding custom error pages

---

app/views/recipes/show.html.erb

- Navbar not displayed and appears when reaching Ingredients on show page of recipe

Navbar not displayed and appears when reaching Ingredients on show page of recipe

---

app/assets/stylesheets/pages/_home.scss
app/views/categories/index.html.erb
app/views/recipes/show.html.erb

Deleted the left and right margin of -15px on the row class as it was creating a border of 15 px

Deleted the left and right margin of -15px on the row class as it was creating a border of 15 px

---

app/views/devise/sessions/new.html.erb

Changed the login button to green - same as the log in with Fb

Changed the login button to green - same as the log in with Fb

---

app/assets/stylesheets/pages/_home.scss
app/views/devise/passwords/new.html.erb

Changing size of texts sign up and forgot password on log in page

Changing size of texts sign up and forgot password on log in page

---

app/assets/stylesheets/components/_recipe_show.scss
app/views/recipes/show.html.erb

Designshow

---

app/assets/stylesheets/components/_banner.scss
app/views/recipes/index.html.erb

Deleting padding right and left of image on recipe show as the blank space was not equal left and right

Deleting padding right and left of image on recipe show as the blank space was not equal left and right

---

app/assets/stylesheets/pages/_dashboard.scss
app/views/carts/index.html.erb
app/views/shared/_dashboard_card.html.erb

"Resized the dislike button on the profile page"

Resized the dislike button on the profile page

---

app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_recipe_show.scss
app/views/devise/registrations/new.html.erb
public/404.html
public/422.html
public/500.html

- Font family enriqueta to all titles
- Log in button and log in page changes

Last details
